name: Renovate

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

  workflow_dispatch:
    inputs:
      args:
        description: 'Optional renovate args, they replace the defaults and disable autodiscover'
        required: false
        type: string

enable-email-notifications: false

env:
  RENOVATE_DRY_RUN: ${{ ((github.event_name != 'schedule' && github.event_name != 'workflow_dispatch')) && 'full' || '' }} # dry-run on main to eleminate race condition
  RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG }}

jobs:
  forgejo:
    runs-on: docker
    container:
      image: data.forgejo.org/renovate/renovate:42.78.1@sha256:103616affd18d8d6fa74d0d63d9826697883d387ac1e4787cc991461f4075e0d
      options: --tmpfs /tmp:exec

    steps:
      - uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false

      - name: print node heap
        run: /usr/local/renovate/node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'

      - name: Renovate
        run: |
          renovate ${{ env.INPUT_ARGS }}
        env:
          GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
          LOG_LEVEL: debug
          RENOVATE_ENDPOINT: ${{ github.server_url }}
          RENOVATE_PLATFORM: forgejo
          RENOVATE_REPOSITORY_CACHE: 'enabled'
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GIT_AUTHOR: 'Renovate Bot <renovate-bot@code.f2n.me>'

          RENOVATE_X_SQLITE_PACKAGE_CACHE: true

          GIT_AUTHOR_NAME: 'Renovate Bot'
          GIT_AUTHOR_EMAIL: 'renovate-bot@code.f2n.me'
          GIT_COMMITTER_NAME: 'Renovate Bot'
          GIT_COMMITTER_EMAIL: 'renovate-bot@code.f2n.me'

          INPUT_ARGS: ${{ inputs.args || (github.repository != 'renovate/renovate' && github.repository) || '' }}

          # use direct connection for these domains for renovate go datasource instead of the go proxy
          # allows faster lookups
          GONOPROXY: code.forgejo.org
